services:
  - type: web
    name: finedot-bot
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /health
    envVars:
      - key: TOKEN
        sync: false
      - key: SPREADSHEET_ID  
        sync: false
      - key: SERVICE_ACCOUNT_JSON
        sync: false
      - key: SPEECH_LANGUAGE
        value: uk-UA
      - key: LOG_LEVEL
        value: INFO
      - key: PORT
        value: 10000